Validate interface name length
EdenGri/SONiC pull request #5
Opened 2023-05-08 13:06 UTC by EdenGri

This HLD document is describing the validation of the interface's name's length.

Related PRs:

| PR title | State | Context |
| :---: | :---: | :---: |
||||

2023-05-09 16:15 UTC, dprital requested changes

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +The kernel can't configure interfaces with names that are longer than `IFNAMSIZ` (`IFNAMSIZ` is the maximum buffer size needed to hold an interface name, including its terminating zero byte.). Since
byte. - Remove the dot ('.')

"...add validation to the SONiC...." - Just "add validation"

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +These are the interfaces that the is user able to config:
Please rephrase: "These are the interfaces available to be configured by CLI, hence, sanity on the interface name is required"

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +if len(vxlan_name) > 15:
We should not use direct number here. Please use IFNAMSIZ. If this constant is not available for this file, you should define one and add in a comment that this constant is based on "IFNAMSIZ "

in addition, I suggest to give the user a feedback, what should be the max length of interface name.

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +The following interface already has validation and we don't need to add an additional check:
"...and we don't need to add **an** additional check..." --> ".....and we don't need to add additional check"

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +The user can configure vlan via CLI command, for example: "config vlan add 100". Valid vlan name is "Vlan"+{vid}. There is a limitation in the CLI command that the vid will not be greater than 4096.
Actually, not greater than "Vlan_4096". lets accurate

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +interface | file path | function name | need to add validation? | example for CLI command |
Please add a comment that "need to add validation" will be set to yes for interfaces that currently doesn't have validation implemented while all the rest have, so it will be clear that all interfaces name need validation, for some of them we already have

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +The following interfaces don't have validation of the interface name in their Yang therefore we will add one:
Yang **model**

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +The following interfaces don't have unit test cases that check the configuration of the interface with too long interface name therefore we will add one:
"interface with too long interface name" -> "that exceed the allowed length of interface name"

Same as for the itemes below

2023-05-09 16:15 UTC, dprital commented on doc/validate_interface_name_length.md
> +The following interfaces don't has a Yang test that check configuration of interface with a too long interface name therefore we will add one:
"too long" -> please rephrase

2023-05-16 05:51 UTC, EdenGri commented on doc/validate_interface_name_length.md
> +The user can configure vlan via CLI command, for example: "config vlan add 100". Valid vlan name is "Vlan"+{vid}. There is a limitation in the CLI command that the vid will not be greater than 4096.
Changed to make it clearer:
`This limitation promises us the vlan name max length is 8 characters and therefore will not cross the 'IFNAMSIZ'`

2023-05-16 08:58 UTC, dprital requested changes

2023-05-16 08:58 UTC, dprital commented on doc/validate_interface_name_length.md
> +The user can configure vlan via CLI command, for example: "config vlan add 100". Valid vlan name is "Vlan"+{vid}. There is a limitation in the CLI command that the vid will not be greater than 4094.
"will not cross the 'IFNAMSIZ'" which is 16

2023-05-16 08:58 UTC, dprital commented on doc/validate_interface_name_length.md
> +The user can configure vrf via CLI command, for example: "config vrf add Vrf100". Valid vrf name must begin with 'Vrf' or named 'mgmt'/'management' in case of ManagementVRF. There is a limitation in
"promises us the vlan name length will not cross the `IFNAMSIZ`" which is 16 by definition

2023-05-16 08:58 UTC, dprital commented on doc/validate_interface_name_length.md
> +The user can configure loopback via CLI command, for example: "sudo config loopback add Loopback11". There is a limitation in the CLI command that the loopback name length will be less than 11. This
"will not cross the `IFNAMSIZ`" (16)

2023-07-18 07:14 UTC, closed without merging